version: '3'
services:
  nginx:
    build: ./nginx
    container_name: sati_nginx
    ports:
      - 8080:8080
    expose:
      - "8080"
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    tty: true

  backend: &app_base
    build: ./backend
    container_name: sati_backend
    command: bin/rails s -b "0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/sati
      - bundle_dir:/usr/local/bundle
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      RAILS_ENV: development
    tty: true

  spring:
    <<: *app_base
    container_name: sati_spring
    command: spring server
    ports: []

  db:
    image: mysql:5.7.10
    container_name: sati_mysql
    environment:
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - sati-mysql-data:/var/lib/mysql
    tty: true

volumes:
  sati-mysql-data:
  bundle_dir:
    driver: local